input:
  label: ""
  kafka:
    addresses:
      - kafka:9092
    topics:
      - "casino-event"
      - "casino-event-add-player"
      - "casino-event-description"
    target_version: 2.1.0 # No default (optional)
    consumer_group: ""
    checkpoint_limit: 1024

#pipeline:
#  processors:
#    -

# Configure tracing with OTel
tracer:
  open_telemetry_collector:
    grpc: [ "lgtm-stack:4317" ] # No default (required)


output:
  resource: buz

# Json logger
logger:
  level: INFO
  format: json