kafka:
  brokers: kafka:9092
  groupId: casino-currency

cache:
  address: redis:6379
  password: ""
  db: 0

exchangeApi:
  #url: https://api.exchangerate.host
  url: https://api.apilayer.com/exchangerates_data
  apiKey: Kd5I6oeaVwAvMyYjqFSJz41rrr6GkzyC
