name: "Build service"
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - '.vscode/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - 'scripts/**'
      - 'assets/**'
      - '*.md'
    tags:
      - v*

  workflow_dispatch:

jobs:
  build-service:
    name: "Build the service"
    uses: ./.github/workflows/build.yaml
    with:
      service: service
      docker_repository: service
      dockerfile: "./build/Dockerfile_log"
