name: "Build service"
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'docs/**'
      - '.run/**'
      - '.vscode/**'
      - 'api/**'
      - 'features/**'
      - 'config/**'
      - 'deployments/**'
      - 'scripts/**'
      - 'assets/**'
      - '*.md'
    tags:
      - v*

  workflow_dispatch:

jobs:
  build-generator-service:
    name: "Build the generator"
    uses: ./.github/workflows/build.yaml
    with:
      service: generator
      docker_repository: generator
      dockerfile: "./build/Dockerfile_generator"

  build-log-service:
    name: "Build the log service"
    uses: ./.github/workflows/build.yaml
    with:
      service: log
      docker_repository: log_service
      dockerfile: "./build/Dockerfile_log"

  build-description-service:
    name: "Build the description service"
    uses: ./.github/workflows/build.yaml
    with:
      service: description
      docker_repository: description_service
      dockerfile: "./build/Dockerfile_description"

  build-currency-service:
    name: "Build the currency service"
    uses: ./.github/workflows/build.yaml
    with:
      service: currency
      docker_repository: currency_service
      dockerfile: "./build/Dockerfile_currency"

  build-player-service:
    name: "Build the player service"
    uses: ./.github/workflows/build.yaml
    with:
      service: player
      docker_repository: player_service
      dockerfile: "./build/Dockerfile_player"
